### ISSUE TITLE
Line Wrap for code blocks 

### ISSUE THREAD

**Issue by kbumsik** [kepano/obsidian-minimal-settings#56] opened 2022-10-13 13:35 UTC
Hi, thank you for Minimal Theme!
I hope there was an option to enable line wrap (a.k.a horizontal scroll) for code blocks in preview mode.

This is an example from Atom Theme:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/7823583/195611315-6438a5f8-7264-4a86-9997-aa5cbb2fb7e4.png">

There is a related discussion here: https://forum.obsidian.md/t/disable-code-block-from-horizontal-scrolling/11357

**Comment by kepano** [comment] 2022-10-20 21:51
This is a duplicate of the request reported on the theme repo

**Closed by kepano** 2022-10-20 21:51 UTC
Labels: enhancement
